
import SQL.Queries;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Edgar
 */
public class Ventana extends javax.swing.JFrame {

    String[] columnNames = new String[]{"Product_name", "Sales_total", "Sales_percentage", ""};
    
    DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
    List<Object[]> listItems = new ArrayList<>();
    List<Object> listDetails = new ArrayList<>();
                
    Queries queries = new Queries();
    String query;
    Integer opcion = 0;

    public void refreshTable(List<Object[]> rows) {
        tableModel.getDataVector().removeAllElements();
        revalidate();
        for (Object[] row : rows) {
            tableModel.addRow(row);
        }
    }

    public Ventana(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        cmbOpcion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItems);

        cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleciona una busqueda-", "1", "2", "3", "4", "5", "6", "7" }));
        cmbOpcion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOpcionItemStateChanged(evt);
            }
        });
        cmbOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOpcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOpcionActionPerformed

    private void cmbOpcionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOpcionItemStateChanged
        try {
            opcion = cmbOpcion.getSelectedIndex();
            System.out.println(opcion);
            switch(opcion){
                case 1:
                    query = "SELECT product_name, SUM(amount) SALE_TOTAL, "
                            + "ROUND(((SUM(amount) / SUM(amount) OVER() ) * 100),4) "
                            + "SALE_PERCENTAGE FROM facts_table " 
                            + "GROUP BY(product_name, amount)";
                break;
                case 2: 
                    query = "SELECT customer_name, order_id, weight_class, SUM(quantity) " 
                            + "FROM facts_table " 
                            + "GROUP BY ROLLUP(customer_name, order_id, weight_class)";
                break;
                case 3:
                    query = "SELECT customer_name, category_id, SUM(amount) " 
                            + "FROM facts_table " 
                            + "GROUP BY CUBE(customer_name, category_id)";
                break;
                case 4:
                    query = "SELECT order_id, product_name, quantity, " 
                            + "SUM(quantity) OVER(PARTITION BY order_id) TOTAL " 
                            + "FROM facts_table";
                break;
                case 5: 
                    query = "SELECT DISTINCT product_name, " 
                            + "TO_DATE(('' || DAY || '/' || MONTH || '/' ||YEAR), "
                            + "'dd/MM/YYYY') DATE_SALE, " 
                            + "LAG ( product_name ) OVER ( ORDER BY TO_DATE(('' "
                            + "|| DAY || '/' || MONTH || '/' ||YEAR), 'dd/MM/YYYY')) "
                            + "PRIOR_SALE FROM facts_table\n ORDER BY DATE_SALE";
                break;
                case 6:
                    query = "SELECT customer_id, order_id, product_name, quantity " 
                            + "FROM facts_table "
                            + "MODEL RETURN UPDATED ROWS " 
                            + "PARTITION BY (order_id, customer_id) " 
                            + "DIMENSION BY (product_name, year) " 
                            + "MEASURES(amount, quantity) " 
                            + "RULES(" 
                            + "quantity['Card Holder - 25',2017] = "
                            + "MAX(quantity)['Card Holder - 25', "
                            + "year BETWEEN 2006 AND 2008]*2)";
                break;
            }
            listItems = queries.getList(query);
            tblItems.setModel(tableModel);
            refreshTable(listItems);
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbOpcionItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOpcion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItems;
    // End of variables declaration//GEN-END:variables
}
